// ============================================================================
//  MOTIONSTUDIO CASE STUDY  —  /projects/motionstudio
//  Sourced from ARCHITECTURE.md. Edit this file to grow the page over time.
//  Add demo videos/screenshots to `media` (files go in /public/demos).
// ============================================================================
import type { Media } from "./data";

export const motionstudio = {
  title: "MotionStudio",
  status: "Live · Actively Building",
  year: "2026",
  role: "Personal project · solo build",
  tagline: "A browser-based video editor, built on Remotion.",
  intro:
    "Place text, images, video and audio on a canvas, arrange them on a frame-accurate timeline, animate them, and export to MP4 — in the browser or on the cloud. This page is the living build journal: the architecture, the decisions, and the bugs that taught me something.",

  // Drop demo videos / screenshots here as the build progresses.
  media: [
    { type: "image", src: "/images/MotionStudio.png", caption: "The editor today — canvas, properties panel, frame-accurate timeline" },
  ] as Media[],

  facts: [
    { num: "~5K+", label: "Lines of strict TypeScript" },
    { num: "7", label: "Engines — data & logic, zero UI" },
    { num: "70+", label: "Logically-grouped commits" },
    { num: "4", label: "Infrastructure layers — Vercel · Supabase · AWS Lambda · S3" },
  ],

  // ————— Why Remotion is the foundation —————
  remotion: {
    heading: "Why Remotion is the core bet",
    body:
      "The product renders real video. Remotion gives me frames as a first-class unit, <Sequence> for temporal composition, <Player> for in-app preview, and renderMedia for the actual encode — building a renderer and encoder myself would be months of work that teaches nothing about this product. The interesting engineering is everything I built on top of it:",
    points: [
      "**Frame-based temporal model** — every element carries `startFrame` + `durationInFrames`, mapped 1:1 onto `<Sequence from={startFrame}>`. Visibility is the half-open window `[start, start + duration)`. Frames, not seconds, because Remotion is frame-based and frames are exact — no floating-point drift.",
      "**One shared renderer = guaranteed WYSIWYG** — the editor preview and the Remotion export call the *same* style function, differing only by a `scale` argument (editor < 1, Remotion = 1). WYSIWYG isn't \"we tried to match\" — the preview is *mathematically* the export.",
      "**Animation on Remotion's primitives** — `interpolate` with `extrapolate: 'clamp'` so animations finish instead of extrapolating to infinity, and `spring` for physics (it needs `fps`, because a bounce is real-time). Multiple animations accumulate into one transform — factors multiply, offsets add — the same algebra compositors use.",
      "**Two export paths, one dialog** — a Browser tab (WebCodecs + OfflineAudioContext, in-process, Chrome/Edge only) and a Cloud Render tab (Remotion Lambda on AWS, any device, full 1080p, no local CPU). The same MotionComposition component powers both — the browser path encodes frames directly, the Lambda path renders the same composition in headless Node.",
      "**DOM video vs Remotion video** — the editor previews with a DOM `<video>` (seek on scrub for exact frames, play natively during playback, muted for reliable autoplay); the export uses `<OffthreadVideo>`, which is authoritative.",
    ],
  },

  // ————— The export pivot: from a CLI command to two production paths —————
  export: {
    heading: "The export pivot — from CLI to two production paths",
    story:
      "The original export was a Remotion CLI command generated by the app. It worked — if you were a developer willing to run a terminal command. For an actual end user it was unusable. That gap forced two separate solutions, each with a different tradeoff.",

    paths: [
      {
        name: "Browser export (WebCodecs)",
        subtitle: "Free · unlimited · Chrome/Edge only",
        how:
          "Each frame is rendered to a canvas using the same style.ts function the editor preview uses, then pushed into a VideoEncoder (WebCodecs API). Audio tracks are mixed frame-perfectly using OfflineAudioContext — a Web Audio context that renders faster than real-time, producing a precise AudioBuffer. Video frames and the audio buffer are muxed into an MP4 container using Mediabunny and downloaded directly to the user's device. No server, no round-trip.",
        why:
          "WebCodecs gives hardware-accelerated encoding in the browser. OfflineAudioContext eliminates the timing drift of real-time audio. Mediabunny handles the muxing complexity. The result is frame-perfect, audio-included output with zero infrastructure cost.",
        limits: "Chrome and Edge only (WebCodecs is not in Firefox/Safari). Large projects encode slowly on low-end hardware.",
      },
      {
        name: "Cloud render (Remotion Lambda)",
        subtitle: "Quota-based · any device · 1080p · AWS Lambda",
        how:
          "The user clicks Render in the Cloud Render tab. A Vercel serverless function verifies their JWT, checks their monthly quota against a Supabase renders table, and calls renderMediaOnLambda() from @remotion/lambda-client. A pre-deployed Lambda function (2GB memory, 120s timeout) renders the Remotion composition in headless Node, writes the output MP4 to S3, and returns a download URL. The serverless function polls getRenderProgress() until done, then returns the URL to the client. Media imported into the editor uploads to S3 in the background as soon as it's added — the browser keeps the blob: URL for local preview, and a storageUrl (a public S3 https:// link) is patched onto the asset once the upload completes, so Lambda has a real URL to fetch when it renders.",
        why:
          "This is the production path — the one that works on every device including mobile, Safari, low-end laptops. The render happens on dedicated infrastructure, not in the user's browser tab. The Lambda function is a standard Remotion deployment; the real engineering was the quota gate, the auth layer, and the background S3 upload around it.",
        limits: "2GB memory / 120s Lambda timeout caps how long or heavy a composition can be per render.",
      },
    ],
  },

  // ————— Auth, quota, and guest access —————
  auth: {
    heading: "Auth, quota, and guest access",
    body:
      "Three sign-in paths — Google OAuth, email/password (Supabase, with email confirmation flow), and anonymous guest (no sign-up required, 1 cloud render free). All auth state and actions live in a single useAuth hook; UI components call hook methods and never touch the Supabase client directly.",

    guestAbuse:
      "Anonymous sessions persist in localStorage — clearing it would give a user a new session and another free render. Solved with a device ID cookie: crypto.randomUUID() written to a 1-year cookie on first visit. The cookie survives localStorage clears. The API checks the device_renders table before allowing any anonymous render and records the device ID only after a confirmed successful output URL — failed renders don't consume the free slot.",

    apiLayer:
      "Three Vercel serverless functions (/api/render, /api/quota, /api/upload-url) sit between the client and AWS. Every render request is validated in four ordered gates: (1) JWT verified via Supabase admin client, (2) device cookie checked for anonymous users, (3) monthly render count checked against the renders table, (4) Lambda started — and only after all four pass. A failed render never consumes quota. Shared helpers in api/_lib/ (auth.ts, db.ts, device.ts) keep the handler logic thin and eliminate duplication across endpoints.",

    accountIsolation:
      "Projects are stored locally in IndexedDB. On every auth state change, AuthBridge (a non-rendering component in App.tsx) compares the new user ID to ms_last_user in localStorage. If they differ — a different account logged in, or a sign-out happened — it calls clearAll(), which resets the Zustand store and calls persist.clearStorage() to immediately wipe IndexedDB. User B never sees User A's projects.",
  },

  // ————— Tech stack, with the why —————
  stack: [
    { name: "Remotion", why: "Frames, <Sequence>, <Player>, renderMedia — the video engine. The one dependency the product is genuinely built around." },
    { name: "React 19 + TypeScript (strict)", why: "Discriminated-union element types; adding a new element type = one type + one renderer." },
    { name: "Zustand", why: "Global state with zero boilerplate: one create() → a hook + selectors. No providers, no reducers." },
    { name: "React Router v7", why: "/ dashboard, /editor/:projectId — the URL is the single input that selects a project." },
    { name: "react-moveable", why: "Drag/resize/rotate handles are a solved problem; rebuilding them is weeks of hit-testing math that teaches nothing about this product." },
    { name: "Tailwind v4 + shadcn/ui", why: "Fast, consistent dark UI via design tokens; accessible primitives (Dialog, Popover, Select) without reinventing them." },
    { name: "IndexedDB + localStorage", why: "Client-only persistence, split by data shape: small JSON state in localStorage, large media blobs in IndexedDB." },
    { name: "Supabase", why: "Auth (Google OAuth, email/password, anonymous) + renders table for quota tracking. Service-role key stays server-side; publishable key in the browser." },
    { name: "Vercel serverless", why: "Two API endpoints: /api/render (Lambda trigger + quota gate) and /api/quota (render count). Node.js, deployed alongside the SPA." },
    { name: "Remotion Lambda", why: "Cloud render path — headless Node on AWS Lambda, returns an S3 MP4 URL. Setup was configuration, not infrastructure engineering." },
    { name: "PostHog + Vercel Analytics", why: "Typed analytics.ts module captures every key event (auth methods, export starts/completions with duration, tab switches, undo/redo). PageTracker fires $pageview on every SPA route change." },
  ],

  // ————— Architecture —————
  architecture: {
    heading: "Two layers, one rule",
    diagram: `engines/   own DATA + LOGIC   (no UI)
features/  own UI             (compose engines)`,
    rule:
      "The Project is the aggregate root. One Project object owns all data — elements, assets, settings. Engines don't keep their own copies; they expose verbs that read and write the one Project through a single mutation point (updateProject). Everything downstream falls out of this: undo/redo hooks the one mutation point and covers every edit automatically, autosave persists the one Project with nothing to wire per-feature, and state drift is impossible because there's only ever one source of truth.",
    movesTitle: "The three data moves — immutability everywhere",
    moves: `add     → [...arr, x]
remove  → arr.filter(x => x.id !== id)
update  → arr.map(x => x.id === id ? { ...x, ...patch } : x)`,
    movesWhy:
      "React and Zustand detect change by reference identity, and undo snapshots must stay frozen. A single .push() would skip re-renders and corrupt history.",
  },

  engines: [
    { name: "project", owns: "The projects array (aggregate root) + undo history + persistence", note: "The only real store" },
    { name: "editor", owns: "Ephemeral view state: selection, current frame, playing, zoom", note: "Deliberately not persisted" },
    { name: "canvas", owns: "Verbs: addText/Image/Video/Audio, updateElement, removeElement, reorderLayer", note: "A hook, not a store — owns no data" },
    { name: "timeline", owns: "Pure frame ↔ pixel math", note: "Stateless helpers" },
    { name: "animation", owns: "interpolate / spring evaluation + presets", note: "Pure functions" },
    { name: "rendering", owns: "The shared style.ts + Remotion MotionComposition", note: "One renderer, two consumers" },
    { name: "asset", owns: "Upload, metadata probing, blob persistence", note: "Reads/writes project.assets" },
  ],
  enginesWhy:
    "Why some engines are stores and others are hooks: a store owns state (Project, Editor). A hook owns verbs over state it doesn't hold — Canvas and Asset read the active project and write back via updateProject. Keeping element data on the Project, not in the Canvas engine, is the aggregate root enforced.",

  // ————— Core systems —————
  systems: [
    {
      title: "Composition-space coordinates",
      body:
        "Elements are stored in output resolution (16:9 = 1920×1080), not screen pixels; the editor renders a scaled view. The export must match the editor — store coordinates once at final resolution and every view (editor at ~50%, Remotion at 100%) just multiplies by its own scale. This one conversion powers canvas dragging, drop-to-canvas, and scrubbing.",
      code: `data → screen : × scale   (shrink to fit the window)
screen → data : ÷ scale   (grow a drag back to real coords)`,
    },
    {
      title: "Timeline coordinate math",
      body:
        "The same idea, on the time axis. Dragging a clip to retime it is updateElement(id, { startFrame }) — the same verb as canvas dragging, through the same door.",
      code: `pxPerFrame  = trackWidth / totalFrames
frameToX(f) = f × pxPerFrame          (draw a clip / ruler tick)
xToFrame(x) = round(x / pxPerFrame)   (scrub / drag)`,
    },
    {
      title: "Time-based playback clock",
      body:
        "Playback advances by real elapsed time × fps, not currentFrame++ per animation frame. requestAnimationFrame fires at the monitor's rate — 60 or 120Hz, dropping under load — so frame++ would play 30fps content at 60fps on a 60Hz screen. Measuring wall-clock time keeps speed correct on any hardware.",
    },
    {
      title: "Persistence, split by data shape",
      body:
        "Object URLs die on reload, so the bytes are persisted and a fresh URL is minted each session. localStorage can't hold large binaries; IndexedDB is built for Blobs. Editor view state is intentionally not persisted — you don't want to reopen frozen mid-playback.",
      code: `metadata (JSON, small)  → localStorage via Zustand persist
media bytes (binary)    → IndexedDB`,
    },
    {
      title: "Undo/redo — snapshots + coalescing",
      body:
        "History is snapshots of the projects array. Because edits build new objects immutably, snapshots share unchanged sub-objects — no deep copies. Rapid edits within ~500ms coalesce into one step, so a whole drag or a typing burst is one undo. It was nearly free to build, because every edit already flows through updateProject.",
    },
  ],

  // ————— Problems & fixes (the war stories) —————
  problems: [
    {
      problem: "Omit on a discriminated union silently collapses to common fields — updateElement lost content, assetId, and friends with no error.",
      fix: "An ElementPatch type: the intersection of per-member partials, so every field of every union member is patchable.",
    },
    {
      problem: "Remotion's <Composition> inferred props as unknown. An interface isn't assignable to Record<string, unknown> — it could be augmented later; a type alias is.",
      fix: "Changed interface ExportProps to type ExportProps. One keyword, fixed inference.",
    },
    {
      problem: "contenteditable cursor jumped to the start on every keystroke — React re-rendering the element reset the DOM selection.",
      fix: "Set initial text via a ref on mount only, then let onInput push to the store without React re-writing the node.",
    },
    {
      problem: "react-moveable under a scaled canvas: element coords are composition-space but the stage is scaled, so handles and elements disagreed.",
      fix: "Drive drag/resize with client-pixel deltas ÷ scale, committing composition coords on release.",
    },
    {
      problem: "Layer reorder did nothing. The first attempt shuffled array order — but stacking is driven by zIndex, not array order.",
      fix: "Rewrote it to reassign contiguous zIndex values.",
    },
    {
      problem: "Undo restored dead blob: URLs — asset rehydration went through updateProject and entered history.",
      fix: "Rehydration became a silent update ({ history: false }).",
    },
    {
      problem: "White-on-white text: default text color was #ffffff on a white canvas. Invisible, and no error anywhere.",
      fix: "A default that contrasts with the canvas — and a lesson that \"no crash\" ≠ \"correct.\"",
    },
    {
      problem: "supabase-js .throwOnError() on count queries returned an error object with an empty message string — impossible to debug.",
      fix: "Replaced the supabase-js query with a direct fetch() to the Supabase REST API with explicit apikey and Authorization headers. The same query, raw HTTP, returned the actual error. Lesson: the abstraction was hiding the signal.",
    },
    {
      problem: "Supabase's new sb_secret_ key format caused 403s on the renders table even with the correct key value.",
      fix: "Switched back to the older JWT eyJ... format keys from the Supabase dashboard. The new format wasn't compatible with the supabase-js version in use.",
    },
    {
      problem: "renderMediaOnLambda() failed with 'remotion-lambda-role not found' despite correct AWS credentials.",
      fix: "The IAM role must be created manually: AWS Console → Roles → Create role → Lambda use case → attach the inline policy from npx remotion lambda policies role. The Remotion CLI doesn't create it.",
    },
    {
      problem: "Version mismatch: remotion at 4.0.483, @remotion/lambda-client at 4.0.488. Silent failures, no helpful error.",
      fix: "Pinned all Remotion packages to the exact same version (removed ^ prefix in package.json). Remotion packages must be at the exact same version across the tree.",
    },
    {
      problem: "404 after Google OAuth redirect on Vercel — the SPA route /dashboard didn't exist as a file.",
      fix: "Added a catch-all rewrite to vercel.json: { source: '/(.*)', destination: '/index.html' }. React Router handles routing client-side; Vercel just needs to serve index.html for every non-API path.",
    },
    {
      problem: "RLS blocked the service_role key from inserting into the renders table, even though service_role is supposed to bypass RLS.",
      fix: "The table was created with 'Automatically expose new tables' OFF, so the service_role had no grants at all. Explicit GRANT SELECT, INSERT, UPDATE, DELETE ON public.renders TO service_role was required.",
    },
  ],

  // ————— Honest limitations —————
  tradeoffs: [
    "Editor audio/video preview is muted and autoplay-dependent; the export is authoritative for sound and timing.",
    "No scene grouping yet — sequencing is done by positioning clips on the timeline.",
    "Fonts fall back to system sans-serif in the Node render (not bundled yet).",
  ],

  payoffs: [
    { decision: "Project as aggregate root", payoff: "Undo/redo + autosave added at one point, covered everything" },
    { decision: "Engines own verbs, not state", payoff: "No state drift; features stayed thin and composable" },
    { decision: "One shared renderer", payoff: "WYSIWYG guaranteed, not hoped for" },
    { decision: "Composition-space coords", payoff: "Editor preview = export, at any zoom" },
    { decision: "Frames + <Sequence>", payoff: "Timeline maps directly onto Remotion; export just works" },
    { decision: "Immutable updates", payoff: "Cheap undo (structural sharing) + reliable re-renders" },
    { decision: "Discriminated-union elements", payoff: "New element type = one type + one renderer" },
    { decision: "Centralized useAuth hook", payoff: "Zero auth logic leaks into UI components — they call hook methods, never Supabase directly" },
    { decision: "Typed api client (apiClient.ts)", payoff: "Bearer token injection is automatic — impossible to forget on a new endpoint" },
    { decision: "Device ID cookie for guest limiting", payoff: "Abuse prevented without requiring accounts — localStorage clears don't help" },
    { decision: "AuthBridge + clearAll()", payoff: "Data isolation between users on a shared device, with no per-feature wiring" },
    { decision: "Record device render after success", payoff: "Failed Lambda renders don't consume the guest's one free slot" },
    { decision: "Background S3 upload + storageUrl patch", payoff: "Uploaded media now renders on Lambda too — blob: URLs stay local for preview, S3 URLs go to the cloud path" },
  ],

  lessons: [
    "A single mutation path is a superpower — it's what made undo, autosave, and WYSIWYG cheap. Decide where data changes before deciding how.",
    "Store data in the target domain (output resolution, frames), not the view's units — views come and go, the data shouldn't.",
    "\"No error\" isn't \"correct\" — white-on-white text and silent Omit-on-union both shipped zero warnings.",
    "Buy the boring parts (moveable handles, encoding) and build the parts that are actually your product: the composition model, the timeline, the animation system.",
    "The CLI export was always the wrong tool for end users — they can't run terminal commands. The gap wasn't a missing feature; it was a missing distribution model. Building both the browser path and the Lambda path was the actual product work.",
    "Remotion Lambda: a cloud render pipeline was 20 minutes of configuration, not months of infrastructure. The interesting engineering was the quota gate, the auth layer, and the device cookie — not the renderer itself. Know what to buy.",
    "Never trust the client. JWT is verified server-side first, quota checked second, Lambda called third — always in that order. The client supplies the token; the server decides what it means.",
    "Abstractions that hide errors are worse than no abstraction. supabase-js returning an empty error string sent us down a 2-hour debugging path. The direct fetch to the REST API returned the actual problem in 10 seconds.",
  ],
};
